import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    logoText: {
        fontSize: 40,
        fontWeight: "800",
        marginTop: 150,
        marginBottom: 30,
        textAlign: "center",
    },
    loginFormTextInput: {
        height: 43,
        fontSize: 14,
        borderRadius: 5,
        borderWidth: 1,
        borderColor: "#eaeaea",
        backgroundColor: "white",
        paddingLeft: 10,
        marginTop: 5,
        marginBottom: 5,
    },
    button: {
        backgroundColor: "#3897f1",
        borderRadius: 5,
        height: 45,
        marginTop: 10,
        width: '100%',
        alignItems: "center",
        justifyContent: "center",
    },
    iconContainer: {
        borderRadius: 15,
        width: 80,
        height: 80,
        alignItems: 'center',
        justifyContent: 'center',
    },
    iconWrapper: {
        alignItems: 'center',
        marginTop: 80,
        marginBottom: 30,
    },
    welcomeText: {
        fontSize: 26,
        fontWeight: 'bold',
        alignSelf: 'center',
        marginBottom: 10,
    },
    subtitleText: {
        fontSize: 18,
        opacity: 0.6,
        fontWeight: '600',
        alignSelf: 'center',
    },
    inputWrapper: {
        backgroundColor: 'white',
        marginHorizontal: 20,
        borderRadius: 10,
        padding: 10,
        marginTop: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    forgotPasswordText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#3897f1',
        textAlign: 'right',
        marginVertical: 10,
    },
    buttonTouchable: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
    },
    footerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 30,
    },
    footerText: {
        fontSize: 16,
        fontWeight: '600',
        opacity: 0.6,
    },
    footerLink: {
        fontSize: 16,
        fontWeight: '600',
        color: '#3897f1',
    },
    bottomText: {
        textAlign: 'center',
        fontSize: 14,
        fontWeight: '600',
        opacity: 0.7,
    },
    profileContainer: {
        flex: 1,
        backgroundColor: 'white',  // ở component set lại
    },
    fullNameText: {
        fontSize: 32,
        fontWeight: 'bold',
        color: 'white',
        marginTop: 10,
    },
    usernameText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        marginVertical: 10,
    },
    roleBadge: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'white',
        borderRadius: 50,
        marginBottom: 20,
    },
    roleBadgeIcon: {
        color: '#9B30FF',
    },
    roleBadgeText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#9B30FF',
        marginLeft: 10,
    },
    infoSection: {
        paddingHorizontal: 15,
        marginTop: 20,
    },
    infoSectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginVertical: 15,
    },
    userInfoRow: {
        marginTop: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    userInfoLabelContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    userInfoIcon: {
        color: '#9B30FF',
    },
    userInfoLabelText: {
        fontSize: 18,
        marginLeft: 15,
    },
    userInfoValueText: {
        fontSize: 18,
    },
    buttonPrimary: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        backgroundColor: 'rgba(152, 70, 250, 0.8)',
        paddingVertical: 10,
        borderRadius: 15,
    },
    buttonPrimaryText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 15,
    },
    buttonSecondary: {
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 0, 0, 0.7)',
        paddingVertical: 10,
        borderRadius: 15,
        marginTop: 10,
    },
    buttonSecondaryText: {
        color: 'rgba(255, 0, 0, 0.7)',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 15,
    },
})